/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  created_at: Generated<Timestamp>;
  first_name: string;
  id: Generated<Int8>;
  language: Generated<string>;
  last_name: string | null;
  premium: Generated<boolean>;
  profile_photo: string | null;
  user_id: Int8;
  username: string | null;
}

export interface DB {
  users: Users;
}
